### ISSUE TITLE
Use case: Creating a notification for a note.

### ISSUE THREAD

**Issue by Pablito2020** [ToDoTurtle/ToDoTurtle#20]
This use case will receive a noteIdentifier and a date, and then:
1) Will search if the note exists on the NoteRepository, if it doesn't will throw an exception (NoSuchNoteException? See the note package for the current name).
2) Will search on  NotificationRepository for all the notifications related with this note. 
3) If one of the notifications has the same date as the one we want to add, will throw an exception (AlreadyExistingNotificationException?)
4) If the note exists and there isn't a notification with the same date, it will create the Notification object and save it to the NotificationRepository.

**Comment by oriolagobat** [comment]
We should find a way to incorporate the time zone in the notification. This way we can also contemplate time-zone changes (e.g. the user moves to another country while having a notification set up). We could also implement some automatic time-change detector to implement this change.

**Comment by Pablito2020** [comment]
Yes, the date value object can encapsulate all the time-zone logic, and make sure that all the notifications objects are saved inside the repository with a default timezone assigned (for example, the Madrid one).

The use case could receive: The noteIdentifier, the date (maybe in unix timestamp format?) and the timezone of the date.
Then the use case would do:

1. Will search if the note exists on the NoteRepository, if it doesn't will throw an exception (NoSuchNoteException? See the note package for the current name).
2. Will create a date object.
3. Will search on NotificationRepository for all the notifications related with this note.
4. If one of the notifications has the same date as the one we want to add, will throw an exception (AlreadyExistingNotificationException?)
5. If the note exists and there isn't a notification with the same date, it will create the Notification object and save it to the NotificationRepository.
