### ISSUE TITLE
Use case: Adding a deadline given a note identifier and a date.

### ISSUE THREAD

**Issue by Pablito2020** [ToDoTurtle/ToDoTurtle#31]
This use case should receive a note identifier and a date object, and must:
- Check if a deadline is already configured for this note, if it is, throw an exception and don't add it to the repository
- Save the deadline to the repository.

**Comment by FerranAD** [comment]
Don't you think the use case should also check if the provided note identifier exists and throw an expection if it doesn't? I say this since we're expecting notifications to behave like this #20:

>This use case will receive a noteIdentifier and a date, and then:
>1) Will search if the note exists on the NoteRepository, if it doesn't will throw an exception (NoSuchNoteException? See the note >package for the current name).

**Comment by Pablito2020** [comment]
Yes, I think that  adding the note repository as a dependency of the notification use cases makes sense, since a notification doesn't exist without a note (which is the core of our app, so makes sense that is the parent node on the dependency graph).
