### ISSUE TITLE
Use case for creating a device

### ISSUE THREAD

**Issue by Pablito2020** [ToDoTurtle/ToDoTurtle#7]
Devices are those who can trigger the use cases related with reminders, those could be an NFC tag, bluetooth device, etc, etc, etc.

This use case should:
1) Generate a random id for the given device.
2) Create a Device(id, deviceName) object
3) Save it to the DeviceRepository.

**Comment by oriolagobat** [comment]
What about if instead of giving them a name (String, I assume) we give them a field from an enum. This way we would have better control about all the possible variables when naming things.

**Comment by Pablito2020** [comment]
I don't get why we would want an enum and "limit" the type of devices that a user can add. The name is only a "nickname" of the device, not an identifier (which is created automatically by the use case), so we give the user full liberty for choosing  (since we don't know if they want to name it: "Pomodoro NFC Tag" or "Study NFC Tag" or "Patata Tag", etc.)
